#!/bin/sh

echo "                  Seleccione la cuenta a pagar"
read BA 
echo
echo "                  Seleccione el numero de la entidad a utilizar" 
echo "
1: BANRED  
2: REDPAGOS   
"
read entidad

if [ $entidad == 1 ]; then
    enti='BRD'
    fi
if [ $entidad == 2 ]; then
    enti='RPA'
    fi

echo "
1: Pesos Uruguayos  
2: Dolares   

"
read moneda

if [ $moneda == 1 ]; then
    divi='UYU'
    fi
if [ $moneda == 2 ]; then
    divi='USD'
    fi

echo "         Ingresa un monto"
read monto
cerito=00
len=${#monto}

largofijo=13
let cantceros=$largofijo-$len
echo "cantidad de ceros" $cantceros
echo "monto" $monto

for (( c=1; c<=$cantceros; c++ ))
do  
   ceros="0${ceros}"
done
montotal="$ceros$monto$cerito"
echo "monto total" $montotal

olddate=`date +%Y%m%d --date='-7 day'`

echo "fecha vieja:" $olddate
fechahoy=`date +%Y%m%d`
echo "fecha actual:" $fechahoy
contenido="$enti;$BA;;$olddate;$montotal;$divi;"

filename=$enti-$fechahoy'100000'

echo $filename
echo $contenido

echo $contenido>/u02/netcracker/rbm/infinys_root/RBM_int/BEPP/BEPPInputDir/$filename.txt

#BajarProcesos
echo "                                                         ***Matando DCONFIG***"
dconfigadmin -H $HOSTNAME
#killall TM
echo "                                                         ***Matando TM***"
killall TM

#aprontando 
sqlplus $DATABASE << END
	update gparams set name='SYSdateOverride' where name = '#SYSdateOverride';  
	update gparams set name='SYSdateValue' where name = '#SYSdateValue';	
	commit;
	update gparams set STRING_VALUE ='$fechahoy 100000' where name = 'SYSdateValue';
	quit
    exit
END

#GENEVA_FIXEDDATE tiene el mismo de fecha y hora que SYSdateValue
export GENEVA_FIXEDDATE=''$fechahoy' 10000000' 
echo $GENEVA_FIXEDDATE 

#LevantarProcesos
echo "                                                         ***Levantando DCONFIG***"
nohup DConfigAgent &
sleep 0.5
echo "                                                         ***Levantando los SITTER*** "
sitter -N RBMPROD -s BG_1
sitter -N RBMPROD -s BG_2
sitter -N RBMPROD -s BG_3 
sitter -N RBMPROD -s BC 
sitter -N RBMPROD -s FID 
sitter -N RBMPROD -s FID.GSM 
sitter -N RBMPROD -s FID.SMSC 
sitter -N RBMPROD -s FID.GRE 
sitter -N RBMPROD -s RMFP_1 
sitter -N RBMPROD -s RMFP_2 
sitter -N RBMPROD -s RMFP_3 
sitter -N RBMPROD -s RMFP_4 
sitter -N RBMPROD -s RMFP_5 
sitter -N RBMPROD -s RMFP_6 
sitter -N RBMPROD -s RMFP_7 
sitter -N RBMPROD -s RMFP_8 
sitter -N RBMPROD -s RMFP_9 
sitter -N RBMPROD -s RMFP_10 
sitter -N RBMPROD -s RMFP_11 
sitter -N RBMPROD -s RMFP_12 
sitter -N RBMPROD -s RMFP_13 
sitter -N RBMPROD -s RMFP_14 
sitter -N RBMPROD -s RMFP_15 
sitter -N RBMPROD -s CEU_01 
sitter -N RBMPROD -s CEU_02 
sitter -N RBMPROD -s CEU_03 
sitter -N RBMPROD -s CEU_04 
sitter -N RBMPROD -s CEU_05 
sitter -N RBMPROD -s RRR_1 
sitter -N RBMPROD -s RRR_2 
sitter -N RBMPROD -s RRR_3 
sitter -N RBMPROD -s RRR_4 
sitter -N RBMPROD -s RRR_5 
sitter -N RBMPROD -s RJR_1 
sitter -N RBMPROD -s RJR_2 
sitter -N RBMPROD -s DUM 
sitter -N RBMPROD -s COA0 
sitter -N RBMPROD -s ODD 
sitter -N RBMPROD -s GOMP 
sitter -N RBMPROD -s EXP 
sitter -N RBMPROD -s CCELoader 
sitter -N RBMPROD -s CASP 
echo
sleep 0.5
echo "                                                         ***Levantando TM***"
TM -u geneva_admin -p M3ch4_A_4su@$ORACLE_SID &
echo
sleep 0.5

echo " Corriendo BEPP" 

BEPP 

#BajarProcesos
echo "                                                         ***Matando DCONFIG***"
dconfigadmin -H $HOSTNAME
#killall TM
echo "                                                         ***Matando TM***"
killall TM

#unset fixeddate
echo
unset GENEVA_FIXEDDATE 

#revirtiendo 
sqlplus $DATABASE << END
	update gparams set STRING_VALUE ='ANY' where name = 'SYSdateValue';   
	update gparams set name='#SYSdateOverride' where name = 'SYSdateOverride';  
	update gparams set name='#SYSdateValue' where name = 'SYSdateValue';  
	commit;
	quit
    exit
END

#LevantarProcesos
echo "                                                         ***Levantando DCONFIG***"
nohup DConfigAgent &
sleep 0.5
echo "                                                         ***Levantando los SITTER*** "
sitter -N RBMPROD -s BG_1
sitter -N RBMPROD -s BG_2
sitter -N RBMPROD -s BG_3 
sitter -N RBMPROD -s BC 
sitter -N RBMPROD -s FID 
sitter -N RBMPROD -s FID.GSM 
sitter -N RBMPROD -s FID.SMSC 
sitter -N RBMPROD -s FID.GRE 
sitter -N RBMPROD -s RMFP_1 
sitter -N RBMPROD -s RMFP_2 
sitter -N RBMPROD -s RMFP_3 
sitter -N RBMPROD -s RMFP_4 
sitter -N RBMPROD -s RMFP_5 
sitter -N RBMPROD -s RMFP_6 
sitter -N RBMPROD -s RMFP_7 
sitter -N RBMPROD -s RMFP_8 
sitter -N RBMPROD -s RMFP_9 
sitter -N RBMPROD -s RMFP_10 
sitter -N RBMPROD -s RMFP_11 
sitter -N RBMPROD -s RMFP_12 
sitter -N RBMPROD -s RMFP_13 
sitter -N RBMPROD -s RMFP_14 
sitter -N RBMPROD -s RMFP_15 
sitter -N RBMPROD -s CEU_01 
sitter -N RBMPROD -s CEU_02 
sitter -N RBMPROD -s CEU_03 
sitter -N RBMPROD -s CEU_04 
sitter -N RBMPROD -s CEU_05 
sitter -N RBMPROD -s RRR_1 
sitter -N RBMPROD -s RRR_2 
sitter -N RBMPROD -s RRR_3 
sitter -N RBMPROD -s RRR_4 
sitter -N RBMPROD -s RRR_5 
sitter -N RBMPROD -s RJR_1 
sitter -N RBMPROD -s RJR_2 
sitter -N RBMPROD -s DUM 
sitter -N RBMPROD -s COA0 
sitter -N RBMPROD -s ODD 
sitter -N RBMPROD -s GOMP 
sitter -N RBMPROD -s EXP 
sitter -N RBMPROD -s CCELoader 
sitter -N RBMPROD -s CASP 
echo
sleep 0.5
echo "                                                         ***Levantando TM***"
TM -u geneva_admin -p M3ch4_A_4su@$ORACLE_SID &
echo
sleep 0.5

echo "                                            PROCESO FINALIZADO!!! " 
